config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
         # has_many :comments

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
 
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
         
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
 
  def following?(user)
    following.include?(user)
  end

  def username
  email.split('@')[0].capitalize
  end

  def useremail
    email.split('@')[0]
  end
      
  
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def about
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    # @tweets = current_user.tweet.build
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @tweet = current_user.tweet.find_by(id: params[:id])
    redirect_to tweets_path, notice: 'Not Authorized' if @tweet.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-fixed-top">
   
    <%= link_to image_tag('/img/logo.png',class:"logo",height:"50",alt:'logo'), root_path ,class:"navbar-brand"%>

    <%= form_tag root_path,class:"form-inline my-2 my-lg-0 search",:method => "get" do %>
    <%= text_field_tag :search,params[:search],class:"form-control mr-sm-2 search-box"%>
    <%= submit_tag "Search",class:"btn btn-outline-primary my-2 my-sm-0"%>
    <% end %>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbar-list-4">
            <ul class="navbar-nav">
            <% if user_signed_in? %>
            

                <li class="nav-item dropdown show">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <%= link_to "My tweets", tweets_path, class:"nav-link dropdown-item" %>
                        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link dropdown-item" %>
                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link dropdown-item" %>
                    </div>
                </li>  


        
                <% else %>
        
                <li class="nav-item">
                    <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
                    </li>
        
                    <li class="nav-item">
                    <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
                    </li>
        
                    
                <% end %>
            </ul>
        </div>
    


    
</nav>

app/views/home/about.html.erb
<h1>About Page</h1>

app/views/home/index.html.erb
<h1>tweets</h1>

<br/>

<% if user_signed_in? %>
  <div class="jumbotron jumbotweet">
    <%= form_with(tweet: @tweet) do |form| %>


      <div class="field commentstyle">
        <strong><%= form.label :Tweet %></strong>
        <%= form.text_area :body,:size=>'100%x0%' , :required => true %>
      </div>

      <!-- <div class="actions commentstyle">
        <%= form.submit %>
      </div> -->
    <% end %>

  </div>
<% end %>


<% @tweets.each do |tweet| %>
  <div class="jumbotron jumbotweet">
    <p class="">
      <%= tweet.user.username %>
      <i class="fa fa-check-circle"></i>
      <small> @<%= tweet.user.useremail %></small>&nbsp&nbsp&nbsp
      <small>&Tab;&Tab;<%= time_ago_in_words(tweet.created_at) %> ago</small>
    </p>
    <small><p><%= time_ago_in_words(tweet.created_at) %> ago</p></small>
    

    <p class="lead">
      <%= tweet.body %>
    </p>
    <br/>
  <% if user_signed_in? && current_user==tweet.user%>
        <%= link_to 'Edit', edit_tweet_path(@tweets) %>

      <%= link_to 'Delete', @tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/3ec71fc36c.js" crossorigin="anonymous"></script>

    <title>Twitter</title>

  </head>
  <body>
    <%= render 'home/header' %>

    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
      
    </div>
      <%= render 'home/footer' %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function () {
          $('.dropdown-toggle').dropdown();
      });
  </script>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field commentstyle">
    <strong><%= form.label :Tweet %></strong>
    <%= form.text_area :body,:size=>'100%x20%' , :required => true %>
  </div>

  <div class="actions commentstyle">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet ,class: "btn btn-outline-primary" %>
<%= link_to 'Back', tweets_path ,class: "btn btn-outline-primary" %>

app/views/tweets/index.html.erb
<h1>tweets</h1>

<br/>

<% @tweets.each do |tweet| %>
  <% if tweet.user == current_user %>
    <div class="jumbotron jumbotweet">
      <p class="">
        <%= tweet.user.username %>
        <i class="fa fa-check-circle"></i>
        <small> @<%= tweet.user.useremail %></small>&nbsp&nbsp&nbsp
        <small>&Tab;&Tab;<%= time_ago_in_words(tweet.created_at) %> ago</small>
      </p>
      <small><p><%= time_ago_in_words(tweet.created_at) %> ago</p></small>
      

      <p class="lead">
        <%= tweet.body %>
      </p>
      <br/>
    <% if user_signed_in? && current_user==tweet.user%>
          <%= link_to 'Edit', edit_tweet_path(@tweets) %>

        <%= link_to 'Delete', @tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  <% end %>
<% end %>


<br/>


<% if user_signed_in? %>
  <%= link_to 'New tweet', new_tweet_path, class:"btn btn-secondary" %>
<% end %>

app/views/tweets/new.html.erb
<h1 class="commentstyle"><u>New tweet</u></h1>
<br/>
<br/>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path ,class: "btn btn-outline-primary"%>

app/views/tweets/show.html.erb
<p>
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tweet.body %>
</p>

<% if user_signed_in? %>
  <% if current_user.username == @tweet.user.username %>
    <p class="commentstyle">
      <%= link_to 'Edit', edit_tweet_path(@tweet),class: "btn btn-outline-primary" %>
    </p>       
    <p class="commentstyle">
        <%= link_to 'Delete', @tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
    </p>
  <% end %>
<% end %>